### ISSUE TITLE
How to use v4l2onvif

### ISSUE THREAD

**Issue by leomatrix** [mpromonet/v4l2onvif#1]
now I can use your v4l2rtspserver demo as a RTSP server on ubuntu, But I don`t know how to use v4l2onvif... could you give me some example usage??

**Comment by mpromonet** [comment]
Hi leomatrix,
You should be able to expose an onvif media streamer starting :

    onvif-server.exe -i <video device > -I <rtsp url >

This should start an onvif web service on port 8080 to acces to the rtsp stream.

If you like to use discovery you may look to ws-discovery project that can publish the onvif URL througt wsd.

Best regards
Michel

**Comment by leomatrix** [comment]
first I run command $v4l2rtspserver /dev/video1  to start a rtsp sever
and then I could use ffplay to get stream, like this : $ffplay -rtsp_transport tcp rtsp://10.32.10.146:8554/unicast
but I still don't know how use tools like "ONVIF Device Test tool" to discover my streamer..., and how to bind onvif interface to rtsp server

**Comment by mpromonet** [comment]
Hi,

To run an onvif service for your rtsp server you can use something like

    onvif-server.exe -i /dev/video1 -I rtsp://10.32.10.146:8554/unicast

Then you should add à device in onvifdm with url http://10.32.10.146:8080 (assuming rtsp server and onvif server run on same host)

If you like to publish the onvif server URL, you can use project ws-discovery running

    server.exe -x http://10.32.146:8080 -t \"http://www.onvif.org/ver10/network/wsdl\":NetworkVideoTransmitter

With this ws service, onvifdm should discovery the onvif service that Will give access to the rtsp service.

Best regards
Michel

**Comment by leomatrix** [comment]
@mpromonet Excuse me! I am a newer on onvif. How should I add à device in onvifdm with url http://10.32.10.146:8080 ??

**Comment by leomatrix** [comment]
Thank you very much! now I can use onvifdm to play rtsp stream! but it seems that there is a problem with ws-discovery...  I run the command :
server.exe -x http://10.32.146:8080 -t \"http://www.onvif.org/ver10/network/wsdl\":NetworkVideoTransmitte
but it seem the sever cannot be found by "ONVIF Device Test tool"

**Comment by mpromonet** [comment]
Hi leomatrix,
Nice that you were able to play the stream with onvifdm.
Did you tried probe.exe to check if ws-discovery service is answering well?
Best regards
Michel

**Comment by quyong123** [comment]
qyq@ubuntu:/work/v4l2onvif-master$ ./onvif-server.exe 
Listening to 8080
SOAP 1.2 fault: SOAP-ENV:Receiver[no subcode]
""
Detail: setsockopt unset IPV6_V6ONLY failed in soap_bind()

why???

**Comment by mpromonet** [comment]
Hi quyong123,
This is seems far away from the subject of this issue, it could be better to open one dedicated to the problem you meet.
Best Regards,
Michel.

**Comment by marat-ab** [comment]
Hello!
I try to run onvif + rtsp on Rasberry Pi by the following sequence:
1. Run v4l2rtspserver:
_>./v4l2rtspserver_
2. Run onvif server:
_> ./onvif-server.exe -i /dev/video0 -I rtsp://192.168.8.196:8554/unicast_

RTSP work fine in VLC! But when I try work in Onvif Device Manager (ODM) I have some trouble: when I add http://192.168.8.196:8080/onvif/device_service into "Device list" and click on it by mouse button, the "Loading" process in the right part of the program take very long time.
In the console I see this:
_Listening to 8080
GetSystemDateAndTime
GetScopes
GetDeviceInformation
GetNetworkInterfaces
GetDNS
GetSystemDateAndTime
GetCapabilities
GetServices
SOAP 1.2 fault SOAP-ENV:Sender[no subcode]
"End of file or no input: message transfer interrupted"
Detail: [no detail]
GetCapabilities
Subscribe_

After a while, when the Loading process in ODM is over, I can see the video stream.
P.S.
I'm using the latest version of gsoap.
___
Best regards
Marat

**Comment by mpromonet** [comment]
Hi Marat,
The issue you describe seems far from the original one, could you please create another one.
It seems GetServices raise an exception.
Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi leomatrix,

I am closing this issue, because now discovery & rtsp are embeded in the project.

Best Regards

Michel.
