### ISSUE TITLE
Erroneous execution

### ISSUE THREAD

**Issue by quyong123** [mpromonet/v4l2onvif#2]
hi:
I use ubuntu14 and ./onvif-server.exe
Listening to 8080
SOAP 1.2 fault: SOAP-ENV:Receiver[no subcode]
""
Detail: setsockopt unset IPV6_V6ONLY failed in soap_bind()
maybe not support IPV6?

**Comment by mpromonet** [comment]
Hi, 
This seems related to the gSOAP release you are using.
Did you looked to https://sourceforge.net/p/gsoap2/bugs/966/ ?
This is an old bug, but maybe you are using an old gSOAP.
Best Regards,
Michel.
