### ISSUE TITLE
PTZ Onvif server

### ISSUE THREAD

**Issue by Kiwa21** [mpromonet/v4l2onvif#3]
Would it be possible to use this app as a ONVIF PTZ server only ?
I need to catch incoming PTZ commands from a client but I don't have a video source

**Comment by mpromonet** [comment]
Hi Gregoire,
The purpose of this project is to expose V4L2 device as ONVIF server.
If you have a V4L2 device driver that implement V4L2_CID_PAN_ABSOLUTE, V4L2_CID_TILT_ABSOLUTE, V4L2_CID_TILL_ABSOLUTE or V4L2_CID_PAN_RELATIVE, V4L2_CID_TILT_RELATIVE, V4L2_CID_ZOOM_RELATIVE, it could work.
Best Regards,
Michel.
