### ISSUE TITLE
Changing Frame Rate

### ISSUE THREAD

**Issue by taospartan** [mpromonet/v4l2onvif#4]
Hi, 
    Im using a rpi zero w, running v4l2rtspserver and v4l2onvif, I successfully can see the rtsp feed and although it takes a long time to load, view the stream in onvif DM. 
However when I try to change the frame rate, resolution or GOP size I am unable to do so, is this the standard behaviour?

many thanks

Tao

**Comment by mpromonet** [comment]
Hi Tao,

I have now integrate RTSP server in this project and the ws-discovery.
Then it is a simpler solution, however changing resolution, framerate are still buggy.
Changing image settings should work.

Best Regards,
Michel.

**Comment by taospartan** [comment]
Many thanks I look forward to testing it!!
