### ISSUE TITLE
Authentication has problem - SOAP 1.2 fault SOAP-ENV:Sender[wsse:FailedAuthentication]

### ISSUE THREAD

**Issue by whitetiger21022014** [mpromonet/v4l2onvif#9]
Thank for your v4l2onvif
I just tested, everything is working so well, but if I use authentication -u and -p, Onvif device manager -> network settings is empty and access to rtsp://192.168.1.182:8554/video201 without password
Docker and compile source code also have the same problem 
Thanks

**Start onvif server**
./onvif-server.exe -u admin -p 12345678 -i /dev/video201

**Run client**
./onvif-client.exe -u admin -p 12345678 http://192.168.1.182:8080

Connecting to http://192.168.1.182:8080
=>Device::GetDeviceInformation
        Manufacturer:5.15.0-52-generic
        Model:Linux
        FirmwareVersion:dc1430e-dirty
        SerialNumber:#58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022
        HardwareId:x86_64
=>Device::GetHostname
SOAP 1.2 fault SOAP-ENV:Sender[no subcode]
""
Detail: [no detail]
=>Device::GetDNS
        DNS:127.0.0.53
=>Device::GetNetworkInterfaces
        ens33 00:c:29:9b:81:ae
        IP:192.168.21.132/24
        ens37 00:c:29:9b:81:b8
        IP:192.168.1.182/24
        docker0 02:42:54:50:53:9a
        IP:172.17.0.1/16
=>Device::GetSystemDateAndTime
        TZ:+07

**Onvif device manager**
Network settings is empty

**Onvif server' log**
GetServiceCapabilities
GetSystemDateAndTime
GetSystemDateAndTime
GetDeviceInformation
GetScopes
GetDNS
GetDeviceInformation
GetNetworkInterfaces
GetHostname
SOAP 1.2 fault SOAP-ENV:Sender[wsse:FailedAuthentication]
"The security token could not be authenticated or authorized"
Detail: Username authentication required

**/etc/hosts**
127.0.0.1       localhost
192.168.1.182   ubuntu

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by mpromonet** [comment]
Hi @whitetiger21022014 

You are right there is a problem in the test, rtsp user is not used for now.

Best Regards
Michel.
